### ISSUE TITLE
Dockest does not work with docker-compose V2

### ISSUE THREAD

**Issue by oscarlgz** [erikengervall/dockest#283]
**Describe the bug**

docker-compose V2 `config` command omits `version` from output. `dockest` cannot run as when validating compose file(s) it expects `version` to be present.

<img width="1126" alt="Skärmavbild 2022-01-31 kl  12 09 47" src="https://user-images.githubusercontent.com/819006/151783592-14ba5299-43ec-40d6-8bb8-2c90f16fed69.png">

See [this issue](https://github.com/docker/compose/issues/8950) for reference.

I'm not sure what would be the best way to remedy this. Possibly just remove the version check in [this line](https://github.com/erikengervall/dockest/blob/53caf2624316fa7ddc84abd90e14dc9b23cbeb10/packages/dockest/src/run/bootstrap/getParsedComposeFile.ts#L59).

**Comment by erikengervall** [comment]
Indeed, ran into this myself recently. I'll give it some though - might release a temporary patch just to get things working again while working on a proper solution.

**Comment by oscarlgz** [comment]
That would be nice 👍

**Comment by erikengervall** [comment]
@oscarlgz give v3.0.1 a try when you've got a chance

works pretty well on my end

**Comment by oscarlgz** [comment]
Works here! Thanks 🎉

**Comment by celiolatorraca** [comment]
Hey!

Bumping to version `3.0.1` solved the version issue, but now it seems that docker-compose reads the `published` ports as string and dockest expects it to be integer

Are you having this issue?

v1 output:
```
stgres:
    environment:
      POSTGRES_DB: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_USER: ...
    image: ...
    ports:
    - published: 5434
      target: 5432
```

v2 output:
```
postgres:
    environment:
      POSTGRES_DB: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_USER: ...
    image: ...
    networks:
      default: null
    ports:
    - target: 5432
      published: "5434"
```
