### ISSUE TITLE
Dockest does not work with docker compose v2

### ISSUE THREAD

**Issue by celiolatorraca** [erikengervall/dockest#298]
**Describe the bug**
The rollout of the docker-compose v2 (which introduced a new CLI `docker compose` - without the dash) works differently.

Dockets try to validate the docker-compose yaml version, but the new CLI does not return it.
When reading the file, some validations fail due to that...

More precisely here: `src/run/bootstrap/getParsedComposeFile.ts`

**To Reproduce**

Here are some examples of the docker compose CLI output:
Using the v2 (also achievable with `docker compose -f ...` (note the missing dash)

docker-compose.yaml
```
version: '3.8'
services:
  postgres:
    image: ...
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_DB: ...

  kafka:
    image: ...
    ports:
      - '9092:9092'
      - '9093:9093'
      - '9094:9094'
      - '9082:8081'
      - '2181:2181'
    command: run -e kafka_hostname="" -e kafka_advertised_hostname=${HOST_IP} -e kafka_auto_create_topics_enable=true

```

```
docker-compose -f <full-path>/docker-compose.yml config
name: service-api
services:
  kafka:
    command:
    - run
    - -e
    - kafka_hostname=
    - -e
    - kafka_advertised_hostname=
    - -e
    - kafka_auto_create_topics_enable=true
    image: ...
    networks:
      default: null
    ports:
    - mode: ingress
      target: 9092
      published: "9092"
      protocol: tcp
    - mode: ingress
      target: 9093
      published: "9093"
      protocol: tcp
    - mode: ingress
      target: 9094
      published: "9094"
      protocol: tcp
    - mode: ingress
      target: 8081
      published: "9082"
      protocol: tcp
    - mode: ingress
      target: 2181
      published: "2181"
      protocol: tcp
  postgres:
    environment:
      POSTGRES_DB: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_USER: ...
    image: ...
    networks:
      default: null
    ports:
    - mode: ingress
      target: 5432
      published: "5434"
      protocol: tcp
networks:
  default:
    name: ..._default
```

With the previous version (or with v2 disabled):
```
services:
  kafka:
    command: run -e kafka_hostname="" -e kafka_advertised_hostname= -e kafka_auto_create_topics_enable=true
    image: ...
    ports:
    - published: 9092
      target: 9092
    - published: 9093
      target: 9093
    - published: 9094
      target: 9094
    - published: 9082
      target: 8081
    - published: 2181
      target: 2181
  postgres:
    environment:
      POSTGRES_DB: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_USER: ...
    image: ...
    ports:
    - published: 5434
      target: 5432
version: '3.8'
```

If we check both outputs, we can see some differences, like the missing `version` attribute and the `published` port as a string.

**Expected behavior**
It should work for both versions of docker-compose.

Locally I can easily disable the v2 feature of the docker-compose, but it's not that easy on our shared Jenkins agent.

**Screenshots**
On Mac you can disable/enable the docker-compose v2 via settings:

![Screen Shot 2022-03-21 at 15 59 20](https://user-images.githubusercontent.com/43214/159291238-d06b1d7a-eba7-4f7f-8b69-f6e0aad0336b.png)

**Desktop:**
 - OS: macOS Monterey
 - Version: 12.2.1

**Docker:**
- Version: 20.10.13, build a224086

**Docker compose (v2 disabled)**
- Version: 1.29.2, build 5becea4c
