### ISSUE TITLE
Could not decode the port mappings. This is most likely related to a breaking change in the docker-compose format.

### ISSUE THREAD

**Issue by edrichhans** [erikengervall/dockest#316]
**Describe the bug**
I'm getting the error:

```
Could not decode the port mappings. This is most likely related to a breaking change in the docker-compose format.
Received: {"mode":"ingress","target":5432,"published":"54320","protocol":"tcp"}
Please report this issue on the dockest issue tracker: https://github.com/erikengervall/dockest/issues
```

It was working completely fine yesterday, then this error started to pop up.
From what I can see, the target port is parsed as `int` while the published port is parsed as `string`

**To Reproduce**

### dockest.ts
```
import { Dockest, logLevel } from 'dockest';
import { createPostgresReadinessCheck } from 'dockest/readiness-check';
import jest from 'jest';

const { run } = new Dockest({
    composeFile: ['docker-compose.test.yml'],
    dumpErrors: true,
    jestLib: jest,
    logLevel: logLevel.INFO,
});

run([
    {
        serviceName: 'postgres',
        readinessCheck: createPostgresReadinessCheck(),
    }
]);
```

### docker-compose.test.yml
```
version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "test"]
      interval: 5s
      timeout: 1s
      retries: 2
```

**Expected behavior**
No error

**Screenshots**
<img width="431" alt="Screen Shot 2022-06-24 at 11 22 43 AM" src="https://user-images.githubusercontent.com/13763624/175455839-027f5936-422c-4c3d-b2a9-f6bcbf36e77f.png">

**Desktop (please complete the following information):**
 - OS: M1 Mac OS
 - Version 11.3

**Additional context**
Packages
```
"ts-node": "^10.8.1"
"dockest": "^3.0.1"
```
Node version v16.15.1
